[package]
name = "evenger"
version = "0.1.0"
authors = ["Eon S. Jeon <esjeon@hyunmu.am>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev-sys = "0.2"
nix = "0.15.0"

[build-dependencies]
bindgen = "0.51.0"
